CREATE TABLE [system].[HCM_PLCs](
	[IdPLC] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[FullDescription] [varchar](100) NULL,
	[ImagePath] [varchar](100) NULL,
	[ImageWidth] [float] NULL,
	[ImageHeight] [float] NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_HCM_PLCs] PRIMARY KEY CLUSTERED 
(
	[IdPLC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_HCM_PLCs_Name] ON [system].[HCM_PLCs]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO 

ALTER TABLE [system].[HCM_PLCs] ADD  CONSTRAINT [DF_HCM_PLCs_Active]  DEFAULT ((1)) FOR [Active]
