CREATE TABLE [to].[HCM_RCP_ErrorCodes](
	[IdRCPErrorCode] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[FullDescription] [varchar](100) NULL,
	[PlcValue] [int] NOT NULL,
	[IsError] [bit] NOT NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_HCM_RCP_ErrorCodes] PRIMARY KEY CLUSTERED 
(
	[IdRCPErrorCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_HCM_RCP_ErrorCodes_PlcValue] UNIQUE NONCLUSTERED 
(
	[PlcValue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_HCM_RCP_ErrorCodes_Name] ON [to].[HCM_RCP_ErrorCodes]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE [to].[HCM_RCP_ErrorCodes] ADD  CONSTRAINT [DF_Rodeo_RCP_ErrorCodes_Active]  DEFAULT ((1)) FOR [Active]
