CREATE TABLE [report].[HCM_Machine_Event_Types](
	[IdMachineEventType] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[FullDescription] [varchar](100) NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_HCM_Machine_Event_Types] PRIMARY KEY CLUSTERED 
(
	[IdMachineEventType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_HCM_Machine_Event_Types_Name] ON [report].[HCM_Machine_Event_Types]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO 

ALTER TABLE [report].[HCM_Machine_Event_Types] ADD  CONSTRAINT [DF_HCM_Machine_Event_Types_Active]  DEFAULT ((1)) FOR [Active]