CREATE TABLE [system].[MSM_PLC_IOs](
	[IdPLCIO] [int] NOT NULL,
	[IdPLCModule] [int] NOT NULL,
	[Position] [int] NOT NULL,
	[Title] VARCHAR(250) NOT NULL,
	[Tagname] [varchar](70) NOT NULL,
	[Bit] [int] NULL,
	[Size] [int]  NOT NULL DEFAULT 0,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_MSM_PLC_IOs] PRIMARY KEY CLUSTERED 
(
	[IdPLCIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_MSM_PLC_IOs] UNIQUE NONCLUSTERED 
(
	[IdPLCModule] ASC,
	[Position] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_MSM_PLC_IOs_Tagname] ON [system].[MSM_PLC_IOs]
(
	[Tagname] ASC,
	[Bit] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE [system].[MSM_PLC_IOs]  WITH CHECK ADD  CONSTRAINT [FK_MSM_PLC_IOs_MSM_PLC_Modules] FOREIGN KEY([IdPLCModule]) REFERENCES [system].[MSM_PLC_Modules] ([IdPLCModule])

GO

ALTER TABLE [system].[MSM_PLC_IOs] CHECK CONSTRAINT [FK_MSM_PLC_IOs_MSM_PLC_Modules]

GO 

ALTER TABLE [system].[MSM_PLC_IOs] ADD  CONSTRAINT [DF_MSM_PLC_IOs_Active]  DEFAULT ((1)) FOR [Active]
