CREATE TABLE [system].[MSM_PLC_VIOs](
	[IdPLCVIO] [int] NOT NULL,
	[IdPLC] [int] NOT NULL,
	[Title] VARCHAR(250) NOT NULL,
	[Tagname] [varchar](70) NOT NULL,
	[Bit] [int] NULL,
	[Order] [int] NOT NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_MSM_PLC_VIOs] PRIMARY KEY CLUSTERED 
(
	[IdPLCVIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_MSM_PLC_VIOs] UNIQUE NONCLUSTERED 
(
	[IdPLC] ASC,
	[Order] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_MSM_PLC_VIOss_Tagname] ON [system].[MSM_PLC_VIOs]
(
	[Tagname] ASC,
	[Bit] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE [system].[MSM_PLC_VIOs]  WITH CHECK ADD  CONSTRAINT [FK_MSM_PLC_VIOs_MSM_PLCs] FOREIGN KEY([IdPLC]) REFERENCES [system].[MSM_PLCs] ([IdPLC])

GO

ALTER TABLE [system].[MSM_PLC_VIOs] CHECK CONSTRAINT [FK_MSM_PLC_VIOs_MSM_PLCs]

GO 

ALTER TABLE [system].[MSM_PLC_VIOs] ADD  CONSTRAINT [DF_MSM_PLC_VIOs_Active]  DEFAULT ((1)) FOR [Active]
