CREATE TABLE [common].[HSM_Brake_Types](
	[IdBrakeType] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[FullDescription] [varchar](100) NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_HSM_Brake_Types] PRIMARY KEY CLUSTERED
(
	[IdBrakeType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_HSM_Brake_Type_PlcValue] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [common].[HSM_Brake_Types] ADD  CONSTRAINT [DF_HSM_Brake_Type_Active]  DEFAULT ((1)) FOR [Active]
GO