CREATE TABLE [common].[Rodeo_Locations_bk20240802] (
    [IdLocation]                  INT           NOT NULL,
    [IdLocationType]              INT           NOT NULL,
    [IdLocationGroup]             INT           NOT NULL,
    [IdLocationRange]             INT           NULL,
    [Name]                        VARCHAR (50)  NOT NULL,
    [FullDescription]             VARCHAR (100) NULL,
    [IdYard]                      INT           NOT NULL,
    [XPos]                        INT           NOT NULL,
    [YPos]                        INT           NOT NULL,
    [ZPos]                        INT           NULL,
    [TheoricalXMin]               INT           NULL,
    [TheoricalYMin]               INT           NULL,
    [TheoricalZMin]               INT           NULL,
    [TheoricalXMax]               INT           NULL,
    [TheoricalYMax]               INT           NULL,
    [TheoricalZMax]               INT           NULL,
    [ZOrder]                      SMALLINT      NOT NULL,
    [DefaultHeading]              SMALLINT      NOT NULL,
    [Row]                         SMALLINT      NULL,
    [Col]                         SMALLINT      NULL,
    [IsVertical]                  BIT           NULL,
    [PlcValue]                    INT           NOT NULL,
    [L3Value]                     VARCHAR (20)  NOT NULL,
    [RCSValue]                    INT           NOT NULL,
    [TOLT]                        INT           NULL,
    [PickupPriority]              INT           NULL,
    [StoragePriority]             INT           NULL,
    [CarPresent_ReadTagname]      VARCHAR (70)  NULL,
    [CarPresent_Bit]              INT           NULL,
    [CarPresent_PlcValue]         INT           NULL,
    [PiecePresent_ReadTagname]    VARCHAR (70)  NULL,
    [PiecePresent_Bit]            INT           NULL,
    [PiecePresent_PlcValue]       INT           NULL,
    [PieceID_ReadTagname]         VARCHAR (70)  NULL,
    [PieceID_WriteTagname]        VARCHAR (70)  NULL,
    [PieceID_TriggerTagname]      VARCHAR (70)  NULL,
    [PieceID_SetpointValue]       INT           NULL,
    [ReadyForPickup_ReadTagname]  VARCHAR (70)  NULL,
    [ReadyForPickup_Bit]          INT           NULL,
    [ReadyForPickup_PlcValue]     INT           NULL,
    [ReadyForStorage_ReadTagname] VARCHAR (70)  NULL,
    [ReadyForStorage_Bit]         INT           NULL,
    [ReadyForStorage_PlcValue]    INT           NULL,
    [AccessRequest_ReadTagname]   VARCHAR (70)  NULL,
    [AccessRequest_Bit]           INT           NULL,
    [AccessRequest_PlcValue]      INT           NULL,
    [AccessGranted_ReadTagname]   VARCHAR (70)  NULL,
    [AccessGranted_Bit]           INT           NULL,
    [AccessGranted_PlcValue]      INT           NULL,
    [Active]                      BIT           NOT NULL
);

