CREATE TABLE [to].[UIB_Jobs] (
    [IdJob]                 BIGINT             NOT NULL,
    [IdJobType]             INT                NOT NULL,
    [IdTOStatus]            INT                NOT NULL,
    [LocationNameBeginReq]  VARCHAR (50)       NULL,
    [IdYardBeginReq]        INT                NULL,
    [XPosBeginReq]          INT                NULL,
    [YPosBeginReq]          INT                NULL,
    [ZPosBeginReq]          INT                NULL,
    [HeadingBeginReq]       SMALLINT           NULL,
    [LocationNameBegin]     VARCHAR (50)       NULL,
    [IdYardBegin]           INT                NULL,
    [XPosBegin]             INT                NULL,
    [YPosBegin]             INT                NULL,
    [ZPosBegin]             INT                NULL,
    [HeadingBegin]          SMALLINT           NULL,
    [LocationNameEndReq]    VARCHAR (50)       NULL,
    [IdYardEndReq]          INT                NULL,
    [XPosEndReq]            INT                NULL,
    [YPosEndReq]            INT                NULL,
    [ZPosEndReq]            INT                NULL,
    [HeadingEndReq]         SMALLINT           NULL,
    [LocationNameEnd]       VARCHAR (50)       NULL,
    [IdYardEnd]             INT                NULL,
    [XPosEnd]               INT                NULL,
    [YPosEnd]               INT                NULL,
    [ZPosEnd]               INT                NULL,
    [HeadingEnd]            SMALLINT           NULL,
    [LocationNameRedirect]  VARCHAR (50)       NULL,
    [IdYardRedirect]        INT                NULL,
    [XPosRedirect]          INT                NULL,
    [YPosRedirect]          INT                NULL,
    [ZPosRedirect]          INT                NULL,
    [HeadingRedirect]       SMALLINT           NULL,
    [FormattedInstructions] VARCHAR (MAX)      NULL,
    [PieceName]             VARCHAR (50)       NOT NULL,
    [HighPriority]          BIT                NULL,
    [Bypasses]              INT                NOT NULL,
    [RequestTime]           DATETIMEOFFSET (7) NOT NULL,
    [BeginTime]             DATETIMEOFFSET (7) NULL,
    [PickupTime]            DATETIMEOFFSET (7) NULL,
    [StorageTime]           DATETIMEOFFSET (7) NULL,
    [EndTime]               DATETIMEOFFSET (7) NULL,
    [CancelTime]            DATETIMEOFFSET (7) NULL,
    [UsernameRequest]       VARCHAR (40)       NULL,
    [UsernameCancel]        VARCHAR (40)       NULL,
    [Notes]                 VARCHAR (MAX)      NULL,
    [InsDateTime]           DATETIMEOFFSET (7) NOT NULL,
    [UpdDateTime]           DATETIMEOFFSET (7) NOT NULL
);

